name: CI

on:
  push:
    # All branches
  pull_request:
    # All pull requests

jobs:
  # Build the project and lint markdown files
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout repository
        uses: actions/checkout@v4

      # Markdown Linting Setup
      - name: Setup | Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup | Cache Bun dependencies
        id: cache-bun
        uses: actions/cache@v4
        env:
          cache-name: cache-bun-modules
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ env.cache-name }}-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-${{ env.cache-name }}-
            ${{ runner.os }}-bun-

      - name: Setup | Install Bun dependencies
        run: bun install --frozen-lockfile

      - name: Action | Lint Markdown
        run: bun run lint:markdown

      # Build Project
      - name: Action | Build Project
        run: bun run build

