name: Deploy Version (Non-Main Branches)

on:
  workflow_run:
    workflows: ["CI"] # Depende del workflow CI
    types:
      - completed
    branches-ignore:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  # Deploy the project
  deploy:
    name: Deploy Version (Non-Main Branches)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
    - name: Deploy | Upload new version to Cloudflare
      id: deploy-step
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}          
        command: version upload

    - name: print deployment-url
      env:
        DEPLOYMENT_URL: ${{ steps.deploy-step.outputs.deployment-url }}
      run: echo $DEPLOYMENT_URL


  # Trigger Indexing Job in n8n workflow after deployment     
  # trigger-indexing:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name:  Setup | Checkout Repository on Release Branch
  #       uses: actions/checkout@v3
        
  #     - name: Action | Trigger Cloudflare Worker
  #       id: trigger-worker
  #       uses: fjogeleit/http-request-action@v1
  #       with:
  #         url: 'https://iarvis.app.n8n.cloud/webhook-test/d7411ae0-f14f-4be3-91d3-683a51d23696'
  #         method: 'POST'
  #         contentType: 'application/json'
  #         data: '{"commit": "${{ github.sha }}"}'
      
  #     - name: Action | Show response
  #       run: |
  #         echo "Worker Response Status: ${{ steps.trigger-worker.outputs.status }}"
  #         echo "Worker Response: ${{ steps.trigger-worker.outputs.response }}"
  #         echo "Status URL: ${{ fromJson(steps.trigger-worker.outputs.response).statusUrl }}"
