name: Deploy Production Version

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  # Deploy the project
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
    - name: Setup | Checkout repository
      uses: actions/checkout@v4

    - name: Setup | Print GitHub SHA
      env:
        GITHUB_SHA: Github SHA ${{ github.sha }}
      run: echo $GITHUB_SHA

    - name: Download | Site artifact
      uses: actions/download-artifact@v5
      with:
        name: site-build-${{ github.sha }}
        path: ./site
      
    - name: Deploy | To Cloudflare (only main branch)
      id: deploy-step
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}    
        wranglerVersion: "4.52.1"      
        command: deploy --assets=./site

    - name: print deployment-url
      env:
        DEPLOYMENT_URL: ${{ steps.deploy-step.outputs.deployment-url }}
      run: echo $DEPLOYMENT_URL

  # Trigger Indexing Job in n8n workflow after deployment     
  # trigger-indexing:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name:  Setup | Checkout Repository on Release Branch
  #       uses: actions/checkout@v3
        
  #     - name: Action | Trigger Cloudflare Worker
  #       id: trigger-worker
  #       uses: fjogeleit/http-request-action@v1
  #       with:
  #         url: 'https://iarvis.app.n8n.cloud/webhook-test/d7411ae0-f14f-4be3-91d3-683a51d23696'
  #         method: 'POST'
  #         contentType: 'application/json'
  #         data: '{"commit": "${{ github.sha }}"}'
      
  #     - name: Action | Show response
  #       run: |
  #         echo "Worker Response Status: ${{ steps.trigger-worker.outputs.status }}"
  #         echo "Worker Response: ${{ steps.trigger-worker.outputs.response }}"
  #         echo "Status URL: ${{ fromJson(steps.trigger-worker.outputs.response).statusUrl }}"
