name: Deploy Preview Version

on:
  workflow_run:
    workflows: ["CI"] # Depende del workflow CI
    types:
      - completed
    branches-ignore:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  actions: read  # Required to download artifacts from another workflow

jobs:
  # Deploy the project
  deploy:
    name: Deploy Preview
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup | Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    
    - name: Setup | Print GitHub SHA
      env:
        GITHUB_SHA: Github SHA ${{ github.event.workflow_run.head_sha }}
      run: echo $GITHUB_SHA

    - name: Download | Site artifact
      uses: actions/download-artifact@v5
      with:
        name: site-build-${{ github.event.workflow_run.head_sha }}
        path: ./site
        github-token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        run-id: ${{ github.event.workflow_run.id }}
        
    - name: Deploy | Upload new version to Cloudflare
      id: deploy-step
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        wranglerVersion: "4.52.1"          
        command: versions upload --assets=./site

    - name: Deploy | Print deployment-url
      env:
        DEPLOYMENT_URL: ${{ steps.deploy-step.outputs.deployment-url }}
      run: echo $DEPLOYMENT_URL
