name: Deploy

on:
  workflow_run:
    workflows: ["CI"] # Depends on successful CI workflow
    types:
      - completed

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  # Build the project and lint markdown files
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout repository
        uses: actions/checkout@v4

      # Markdown Linting Setup
      - name: Setup | Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup | Cache Bun dependencies
        id: cache-bun
        uses: actions/cache@v4
        env:
          cache-name: cache-bun-modules
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ env.cache-name }}-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-${{ env.cache-name }}-
            ${{ runner.os }}-bun-

      - name: Setup | Install Bun dependencies
        run: bun install --frozen-lockfile

      - name: Action | Lint Markdown
        run: bun run lint:markdown

      # Build Project
      - name: Setup | Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.11'

      - name: Setup | Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Action | Build MkDocs site
        run: bun run build

      - name: Deploy | To Cloudflare (only main branch)
        uses: cloudflare/wrangler-action@v3
        if: ${{ github.ref_name }} = "main"
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}          
          command: deploy

      - name: Deploy | To Cloudflare (other branches)
        uses: cloudflare/wrangler-action@v3
        if: ${{ github.ref_name }} != "main"
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}          
          command: version upload

  # Trigger Indexing Job in n8n workflow after deployment     
  # trigger-indexing:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name:  Setup | Checkout Repository on Release Branch
  #       uses: actions/checkout@v3
        
  #     - name: Action | Trigger Cloudflare Worker
  #       id: trigger-worker
  #       uses: fjogeleit/http-request-action@v1
  #       with:
  #         url: 'https://iarvis.app.n8n.cloud/webhook-test/d7411ae0-f14f-4be3-91d3-683a51d23696'
  #         method: 'POST'
  #         contentType: 'application/json'
  #         data: '{"commit": "${{ github.sha }}"}'
      
  #     - name: Action | Show response
  #       run: |
  #         echo "Worker Response Status: ${{ steps.trigger-worker.outputs.status }}"
  #         echo "Worker Response: ${{ steps.trigger-worker.outputs.response }}"
  #         echo "Status URL: ${{ fromJson(steps.trigger-worker.outputs.response).statusUrl }}"
